# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Quick Silver
email: adm@outlook.in
description: > # this means to ignore newlines until "baseurl:"
  I want a free website too!. Mind your clicks, site is under construction.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://akashmahali.github.io" # the base hostname & protocol for your site
twitter_username: akashmahali
github_username:  akashmahali
# Build settings
markdown: kramdown
